services:
  web:
    container_name: web
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - ./web/.env
    volumes:
      - ./web:/app
      - /app/node_modules
    restart: always
    depends_on:
      - notes
      - auth
      - notifications
  notes:
    build:
      context: ./api
      dockerfile: ./apps/notes/Dockerfile
      target: development
    container_name: api-notes
    command: pnpm run start:dev notes
    env_file:
      - ./api/apps/notes/.env
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  auth:
    build:
      context: ./api
      dockerfile: ./apps/auth/Dockerfile
      target: development
    container_name: api-auth
    command: pnpm run start:dev auth
    env_file:
      - ./api/apps/auth/.env
    ports:
      - "3002:3002"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  notifications:
    build:
      context: ./api
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    container_name: api-notifications
    command: pnpm run start:dev notifications
    env_file:
      - ./api/apps/notifications/.env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
